import os
configfile: "config.yaml" 
configfile: "tools.yaml"

localrules: all, samtools_merge

rule all:
    input: "results/dgel.rds"

rule align:
    input:
        fastq = "../fastq/{sample}.fq.gz",
        index = os.path.join(config["star"]["index"], "SA"),
    output: "results/bam/{sample}/Aligned.sortedByCoord.out.bam"
    params:
        index_dir = config["star"]["index"],
        options = config["star"]["options"]
    threads:
        4
    resources:
        mem_mb = lambda wildcards, input: max(5000, input.size_mb + 5000),
        time = lambda wildcards, input: 30 if input.size_mb < 2000 else 360,
    conda: "envs/star.yaml"
    shell:
        """
        STAR --genomeDir {params.index_dir} --runThreadN {threads} {params.options} --readFilesIn {input.fastq} --outFileNamePrefix results/bam/{wildcards.sample}/
        """

rule samtools_merge:
    input: lambda wildcards: expand("results/bam/{sample}/Aligned.sortedByCoord.out.bam", sample=config['groups'][wildcards.group])
    output: "results/merged/{group}.bam"
    threads: 2
    conda: "envs/samtools.yaml"
    shell:
        """
        samtools merge --threads {threads} {output} {input}
        """

rule count:
    input: "results/merged/{sample}.bam"
    output: "results/counts/{sample}.txt"
    params:
        gtf = config["gtf"],
        extra = config["feature_counts"]["options"]
    conda: "envs/subread.yaml"
    shell:
        """
        featureCounts -a {params.gtf} -o {output} {params.extra} {input}
        """

rule DGEList:
    input: expand("results/counts/{sample}.txt", sample=config['groups'])
    output: "results/dgel.rds"
    params:
        names = config['groups']
    conda: "envs/r_edger.yaml"
    script: "scripts/create_dge_list.R"

